config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
  	collection do
  		get :students
  	end
  	collection do
  		get :teachers
  	end
	  resources :courses do
      get :pupils
      get :addpupils
      patch :updatepupils
      patch :deletepupils
  		resources :tasks do
        resources :questions do
          resources :answers
          patch :answerquestion
        end
        patch :makequestion
      end
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#show"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable
  has_many :assignments, :dependent => :destroy
	has_many :roles, :through => :assignments
  has_many :courses, :dependent => :destroy
  has_many :attendants, :dependent => :destroy
  has_many :classes, :through => :attendants, :source => "course" 
  validates :name, :surname, :dni, :birthday, presence: true
  validates :dni, numericality: { only_integer: true }, uniqueness: true
  has_many :questions, :dependent => :destroy
  has_many :answers, :dependent => :destroy
  paginates_per 5
  #after_create :set_default_role

  ransacker :dni do
    Arel.sql("CAST(#{table_name}.dni AS STRING)")
  end

	def has_role?(role_sym)
  	roles.any? { |r| r.name.underscore.to_sym == role_sym }
	end

	def self.all_except(user)
    where.not(id: user)
  end

  def self.students
    select { |u| u.has_role?(:student) }.sort_by { |u| u.surname }
  end

  def self.teachers
    select { |u| u.has_role?(:teacher) }.sort_by { |u| u.surname }
  end

  #private
  #def set_default_role
  #  assignment = Assignment.create(user_id: self.id, role_id: '3')
  #end
  	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user , only: [:show, :edit, :update, :destroy]
  
  # GET /users
  # GET /users.json
  def index
    @q = User.ransack(params[:q])
    @users = @q.result.all_except(current_user).order(:surname).page params[:page]
    if params[:q].blank?
      @users = User.all_except(current_user).order(:surname).page params[:page]
    end
  end

  def students
    @q = User.ransack(params[:q])
    @u = @q.result.all_except(current_user).students
    @users = Kaminari.paginate_array(@u).page(params[:page]).per(5)
    if params[:q].blank?
      @u = User.all_except(current_user).students
      @users = Kaminari.paginate_array(@u).page(params[:page]).per(5)
    end
  end

  def teachers
    @q = User.ransack(params[:q])
    @u = @q.result.all_except(current_user).teachers
    @users = Kaminari.paginate_array(@u).page(params[:page]).per(5)
    if params[:q].blank?
      @u = User.all_except(current_user).teachers
      @users = Kaminari.paginate_array(@u).page(params[:page]).per(5)
    end
  end

  # GET /students
  # GET /students.json

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :surname, :dni, :birthday, :email, :password, role_ids: [])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="container form-style" align="center">
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :apellido %>
    <%= form.text_field :surname %>
  </div>

  <div class="field">
    <%= form.label :dni %>
    <%= form.number_field :dni %>
  </div>

  <div class="field">
    <%= form.label :fecha_de_nacimiento %>
    <%= form.date_select :birthday %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
 
  <% if can? :manage, User %>
  <% for role in Role.all %>
    <div>
      <%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role) %>
      <%=h role.name %>
    </div>
  <% end %>
  <%= hidden_field_tag "user[role_ids][]", "" %>
  <% end %>
  <div class="actions">
    <%= form.submit %>
  </div>
  <br>
<% end %>
</div>

app/views/users/edit.html.erb
<h1 align="center">Editar Usuario</h1>

<%= render 'form', user: @user %>
<br>
<div class="container" align="center"><%= link_to 'Mostrar', @user %>
	<% if @user.id == current_user.id %>| <%= link_to "Cambiar contraseña", edit_user_registration_path %>
	<% end %>
	| <%= link_to 'Atras', @user %> 
 </div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1 align="center">TODOS LOS USUARIOS REGISTRADOS</h1>
<br>
<div class="search-container search">
  <%= search_form_for @q, url: users_path, html: { method: :get } do |f| %>
      <%= f.label :nombre_o_apellido_o_email_o_dni %>
    <%= f.search_field :name_or_surname_or_email_or_dni_cont %>
    <%= f.submit "Buscar" %>
  <% end %>
</div>

<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>

<br>
<table class="table table-bordered style">
  <thead>
    <tr>
      <th class="bg-info text-white" text-align="center">Nombre</th>
      <th class="bg-info text-white">Apellido</th>
      <th class="bg-info text-white">Fecha de nacimiento</th>
      <th class="bg-info text-white">DNI</th>
      <th class="bg-info text-white">Email</th>
      <th class="bg-info text-white">Rol</th>
      <th class="bg-info text-white">Mas informacion</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.surname %></td>
        <td><%= user.birthday %></td>
        <td><%= user.dni %></td>
        <td><%= user.email %></td>
        <td> <% user.roles.each do |r| %>
          <%= r.name %> <% end %>
        </td>
        <td><%= link_to 'Ver detalle', user %> | <%= link_to 'Editar', edit_user_path(user) %> | <%= link_to 'Eliminar', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="container pagination justify-content-center" >
  <%= paginate @users %>
</div>
<br>
<div align="center"><%= link_to 'Ver todos los usuarios', users_path %> </div>

app/views/users/new.html.erb
<h1 align="center">Nuevo Usuario</h1>

<%= render 'form', user: @user %>

<% if @user.has_role?(:teacher) %>
	<%= link_to 'Atras', teachers_users_path %>
<% elsif @user.has_role?(:student) %>
	<%= link_to 'Atras', students_users_path %>
<% end %>

app/views/users/show.html.erb
<div class="container" align="center">
<p id="notice"><%= notice %></p>

<h1>Datos del usuario</h1>
<p>
  <strong>Nombre:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @user.surname %>
</p>

<p>
  <strong>DNI:</strong>
  <%= @user.dni %>
</p>

<p>
  <strong>Fecha de nacimiento:</strong>
  <%= @user.birthday %>
</p>

<p>
 	<strong>Roles:</strong>
 	<ul>
 		<% for role in @user.roles %>
 			<li> <%= role.name %> </li>
 		<% end %>
 	</ul>
</p>

<%= link_to 'Editar', edit_user_path(@user) %> |
<% if can? :manage, User %>
	<%= link_to 'Atrás', users_path %>
<% else %>
	<%= link_to 'Atrás', root_path %>
<% end %>
</div>

app/views/users/students.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">ALUMNOS</h1>
<br>
<div class="search-container search">
  <%= search_form_for @q, url: students_users_path, html: { method: :get } do |f| %>
      <%= f.label :nombre_o_apellido_o_email_o_dni %>
    <%= f.search_field :name_or_surname_or_email_or_dni_cont %>
    <%= f.submit "Buscar" %>
  <% end %>
</div>
<br>
<table class="table table-bordered style">
  <thead>
    <tr>
      <th class="bg-info text-white">Nombre</th>
      <th class="bg-info text-white">Apellido</th>
      <th class="bg-info text-white">Fecha de nacimiento</th>
      <th class="bg-info text-white">DNI</th>
      <th class="bg-info text-white">Email</th>
      <th class="bg-info text-white">Mas informacion</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.surname %></td>
        <td><%= user.birthday %></td>
        <td><%= user.dni %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Ver detalle', user %> | <%= link_to 'Editar', edit_user_path(user) %> | <%= link_to 'Eliminar', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="container pagination justify-content-center" >
  <%= paginate @users %>
</div>

app/views/users/teachers.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">DOCENTES</h1>
<br>

<div class="search-container search">
  <%= search_form_for @q, url: teachers_users_path, html: { method: :get } do |f| %>
      <%= f.label :nombre_o_apellido_o_email_o_dni %>
    <%= f.search_field :name_or_surname_or_email_or_dni_cont %>
    <%= f.submit "Buscar" %>
  <% end %>
</div>

<br>
<table class="table table-bordered style">
  <thead>
    <tr>
      <th class="bg-info text-white">Nombre</th>
      <th class="bg-info text-white">Apellido</th>
      <th class="bg-info text-white">Fecha de nacimiento</th>
      <th class="bg-info text-white">DNI</th>
      <th class="bg-info text-white">Email</th>
      <th class="bg-info text-white">Mas informacion</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.surname %></td>
        <td><%= user.birthday %></td>
        <td><%= user.dni %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Ver detalle', user %> | <%= link_to 'Editar', edit_user_path(user) %> | <%= link_to 'Eliminar', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>