config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
  	collection do
  		get :students
  	end
  	collection do
  		get :teachers
  	end
	  resources :courses do
      get :pupils
      get :addpupils
      patch :updatepupils
      patch :deletepupils
  		resources :tasks do
        resources :questions do
          resources :answers
          patch :answerquestion
        end
        patch :makequestion
      end
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#show"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clasesweb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <% if user_signed_in? %>
        <span> <%= link_to "TTPS-Ruby", root_path %> </span>
        <div class="container nav">
          <% if can? :manage, User %>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Administrar Usuarios </button> 
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item"><%= link_to "Administrar alumnos", students_users_path %></a>
                  <a class="dropdown-item"><%= link_to "Administrar docentes", teachers_users_path %></a>
                  <a class="dropdown-item"><%= link_to "Ver todos los usuarios", users_path %></a>
                </div>
              </div>
          <% end %>
          <% if can? :manage, Course %>
            <span> <%= link_to "Administrar cursos", user_courses_path(current_user) %> </span>
          <% end %>
          <% if current_user.has_role? :student %>
            <div><span> <%= link_to "Mis cursos", user_courses_path(current_user) %></span></div>
          <% end %>
          <div><span> <%= link_to "Mi perfil", current_user %> </span></div>
          <div align="right"><span> <%= link_to "Logout", destroy_user_session_path, method: :delete %> </span></div>
        </div>
      <% else %>
        <div>
          <h2 class="main">Taller de tecnologias de produccion de Software - Ruby</h2>
        </div>
      <% end %>
    </nav>
    <br>
    <%= yield %>
  </body>
</html>